apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ONBOARD_CLIENT_ID: {{ .Values.onboard.clientId  | b64enc | quote }}
  ONBOARD_CLIENT_SECRET: {{ .Values.onboard.clientSecret | b64enc | quote }}
